using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Text;
using BepInEx.Logging;
using HarmonyLib;

namespace SoNY.Ita
{
    /// <summary>
    /// Dictionary entries, actor names and quests do not live in the dialogue database but
    /// in ScriptableObjects generated by Google2u, one column per language (_EN, _FR, _IT
    /// and so on). They cannot be extracted offline because the type trees are stripped,
    /// so they are read at runtime through the TranslationManager getters.
    ///
    /// Writes dump_ui_en.csv with one row per entry: type, numeric id, the enum row name,
    /// the English text and whatever Italian is already present (empty almost everywhere).
    /// That dump is the source for ui_it.csv, which TranslatedTextFallback reloads on
    /// every launch.
    /// </summary>
    internal static class TranslationTableDumper
    {
        // TranslationTypes -> the generated ScriptableObject holding the rows.
        private static readonly Dictionary<string, string> Tables = new Dictionary<string, string>
        {
            { "MenuUI", "MenuUITranslations" },
            { "Quests", "QuestsTranslations" },
            { "DictionaryDatabase", "DictionaryDatabaseTranslations" },
            { "ActorNames", "ActorNamesTranslations" },
            { "Other", "OtherTranslations" },
            { "ActorNamesShadows", "ShadowsActorNamesTranslations" },
            { "DictionaryDatabaseShadows", "ShadowsDictionaryDatabaseTranslations" },
            { "QuestsShadows", "ShadowsQuestTranslations" },
        };

        /// <summary>Returns the number of rows written, 0 when nothing was readable yet.</summary>
        internal static int Write(TranslationManager manager, string dataDir, ManualLogSource log)
        {
            var getTextEn = AccessTools.Method(typeof(TranslationManager), "GetTextEn");
            var getTextIt = AccessTools.Method(typeof(TranslationManager), "GetTextIt");
            if (getTextEn == null)
            {
                log.LogWarning("GetTextEn not found, table dump skipped.");
                return 0;
            }

            var text = new StringBuilder();
            text.Append("Type,textId,Row,EN,IT\n");
            int rows = 0;

            foreach (var table in Tables)
            {
                object type;
                try { type = Enum.Parse(typeof(TranslationManager.TranslationTypes), table.Key); }
                catch { continue; }

                var rowIds = FindRowIds(table.Value);
                if (rowIds == null)
                {
                    log.LogWarning("rowIds not found for " + table.Value);
                    continue;
                }

                foreach (var id in Enum.GetValues(rowIds))
                {
                    int numericId = Convert.ToInt32(id);
                    string english = Read(getTextEn, manager, numericId, type);
                    string italian = getTextIt != null ? Read(getTextIt, manager, numericId, type) : null;
                    if (english == null && string.IsNullOrEmpty(italian)) continue;

                    text.Append(table.Key).Append(',').Append(numericId).Append(',')
                        .Append(ItalianPlugin.Quote(id.ToString())).Append(',')
                        .Append(ItalianPlugin.Quote(english)).Append(',')
                        .Append(ItalianPlugin.Quote(italian)).Append('\n');
                    rows++;
                }
            }

            if (rows == 0) return 0;

            var path = Path.Combine(dataDir, "dump_ui_en.csv");
            File.WriteAllText(path, text.ToString(), new UTF8Encoding(true));
            log.LogInfo(string.Format("Google2u tables: {0} ({1} entries)", path, rows));
            return rows;
        }

        /// <summary>
        /// Finds the rowIds enum nested in a generated ScriptableObject. The generated
        /// classes sit in a namespace, so they have to be matched on the short type name
        /// rather than looked up by the bare name.
        /// </summary>
        private static Type FindRowIds(string tableName)
        {
            // The generated tables live alongside TranslationManager, so try that assembly
            // first and only widen the search if it is not there.
            var found = FindInAssembly(typeof(TranslationManager).Assembly, tableName);
            if (found != null) return found;

            foreach (var assembly in AppDomain.CurrentDomain.GetAssemblies())
            {
                found = FindInAssembly(assembly, tableName);
                if (found != null) return found;
            }
            return null;
        }

        private static Type FindInAssembly(Assembly assembly, string tableName)
        {
            Type[] types;
            // A partially loadable assembly still exposes the types that did resolve.
            try { types = assembly.GetTypes(); }
            catch (ReflectionTypeLoadException e) { types = e.Types; }
            catch { return null; }

            foreach (var type in types)
            {
                if (type == null || type.Name != tableName) continue;
                var rowIds = type.GetNestedType("rowIds", BindingFlags.Public | BindingFlags.NonPublic);
                if (rowIds != null && rowIds.IsEnum) return rowIds;
            }
            return null;
        }

        // A row can be missing entirely: the getter throws instead of returning empty.
        private static string Read(MethodInfo getter, TranslationManager manager, int id, object type)
        {
            try { return (string)getter.Invoke(manager, new object[] { id, type }); }
            catch { return null; }
        }
    }
}
